<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "additional_fsc_styles"
 *
 * Auto generated by Extension Builder 2015-12-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Additional FSC Styles',
	'description' => 'Add additonal style option for Fluid Styled Content Element and headline.',
	'category' => 'frontend',
	'author' => 'Michael Hitzler',
	'author_email' => 'mail@paravista.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'fluid_styled_content' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);